//! # n8n-grpc
//!
//! gRPC service definitions and implementations for n8n-rust.
//!
//! This crate provides:
//! - Protocol buffer generated types
//! - gRPC service implementations
//! - Arrow Flight integration for zero-copy streaming
//! - Hamming similarity service
//! - Multi-transport support (REST, STDIO, gRPC, Flight)
//! - Intelligent content negotiation

pub mod services;
pub mod transport;

// Re-export generated protobuf types
// Note: In a real build, these would be generated by build.rs
// For now, we provide manual implementations
pub mod proto {
    // These would normally be generated by tonic-build
    // For this implementation, we'll define core types manually
    pub use crate::services::*;
}

pub use services::*;
pub use transport::*;
